### PR TITLE
Add Brain syntax to Bric

### PR DESCRIPTION
**Pull request by rafaelcn**
Signed-off-by: Rafael Campos Nunes <rafaelnunes@engineer.com>

### CODE REVIEW

**Comment by rafaelcn** [comment]
Well, this is weird, trying to open a `.brain` file with bric gives `SEGFAULT`. Looking for the error, I'm not sure if it is my code. I don't need to add comments keywords in the `#define brain_syntax`, do I? Everything that's not a keyword in Brain is a comment.

**Comment by rafaelcn** [comment]
There is something I didn't commit yet, I added the brain_syntax to the ` struct editor_syntax highlight_db[]` and that is what gave me SEGFAULT whenever I try to open a `.brain` file.

**Comment by rafaelcn** [comment]
Oh, realized now, the structure `editor_syntax` need to have those parameters. Well, there's something that need to be done, not all languages have multi line comments or even have a keyword for comment at all (as Brain).

**Comment by rafaelcn** [comment]
Although fixed, the syntax highlighter is not working properly as seen below.

image

**Comment by shnupta** [comment]
Thanks for all this work, but please could you make changes and submit them to the vim-change branch. Sorry to be a pain.

**Comment by rafaelcn** [comment]
That's ok, I'll open one in just a few minutes.

**Pull request closed without merging**
