### PR TITLE
Changes in Makefile

### PR DESCRIPTION
**Pull request by doztrock**
I put this PR to propose my idea to make a new Makefile using child Makefiles and building recursively, as I've explained [here](https://github.com/shnupta/bric/issues/73) I've left the websites and information I've researched to build these files.

Hope you  ask me everything about this, I'am available to answer.

Regards

### CODE REVIEW

**Comment by shnupta** [comment]
I've taken a look at the links you've provided in your comment on #73 and I think for now the changes look great.

I'm tempted to move the bric.c and bric.h files to the src/ directory now as to have all source code under that path (as it should be). Then when we split bric.c and bric.h up they will be in sub-components inside src/ .

What I am going to do however is make a new branch for development changes and also a test branch. If you could, please submit this PR to the new development branch.

**Comment by shnupta** [comment]
@doztrock If you take a look at the development branch. I've moved the source files into src/ and also edited the main Makefile to build these into the final executable.

**Comment by doztrock** [comment]
@shnupta Yeah, I've realized that change, so, will we build the file recursivelly as i've proposed before? I mean, should I correct my Makefile or should I close the PR?

**Comment by doztrock** [comment]
I was updating my forked repo, and I was forced to delete my `development` branch. I'll open a new one.

**Pull request closed without merging**
