### PR TITLE
Changes in tag functions based on linked list implementation of editor rows

### PR DESCRIPTION
**Pull request by yashjakhotiya**
Made the changes in tag functions after PR #63. 
Able to merge.
Tried to have history as clean as possible.
Please let me know your feedback after you test this functionality.

### CODE REVIEW

**Comment by shnupta** [comment]
Hi @yashjakhotiya , same comment here as with #68 . I haven't looked through much of your changes yet but could we avoid using 'strdup' to be ANSI C99 compliant. Thanks:)

**Comment by yashjakhotiya** [comment]
Removed strdup as you said! :)

**Comment by shnupta** [comment]
Thank you Yash!:) I'll read through the code tomorrow and Saturday and should merge by Sunday. I'll be merging #68 first though so you'll most likely have to merge those changes. Thank you again!:)

**Comment by shnupta** [comment]
Hi @yashjakhotiya , just merged #68 so waiting on you to merge the new changes. Thanks:)

**Comment by yashjakhotiya** [comment]
I made the required changes. Able to merge. Go ahead!

**Pull request merged**
