### PR TITLE
Some little help

### PR DESCRIPTION
**Pull request by renanrdgsrodrigues**
Sorry about the past PR xP.

"Hello shnupta.
We write some documentations in PT-BR, a brief tutorial about some basic commands to use the editor in the READ.ME, and break the code in more .c and .h to make more easier to understand."

### CODE REVIEW

**Comment by shnupta** [comment]
Hi guys,

Not sure how you merged the master branch to your previous PR branch but we have a few merge conflicts. I'll check them out and get back to you.

**Comment by andy5995** [comment]
@renanrdgsrodrigues soon we will be adding the ability to translate bric into other languages. When that patch is complete, can I ask you to make a translation? It will be a matter of editing a single .po file. It will look similar to this: https://raw.githubusercontent.com/theimpossibleastronaut/rmw/master/po/pt_BR.po

**Comment by renanrdgsrodrigues** [comment]
@andy5995 I actually never saw a document like this. But I accept to try to help.

**Comment by andy5995** [comment]
>@andy5995 I actually never saw a document like this. But I accept to try to help.

Cool. :) If you have any questions along the way, I'd be happy to try and answer them.

Once issue #138 is done, we'll be ready for translations.

@renanrdgsrodrigues Would you create a ticket for adding pt_BR translations? I can then assign it to you, and keep you updated.

**Comment by andy5995** [comment]
Translated comments typically don't go into source code, because that would create far too much extra content in source code files. But we can definitely discuss in the future good methods for creating other translated documentation. @renanrdgsrodrigues You are welcome to [join the newly-created bric chat room](https://join.slack.com/t/bric-editor/shared_invite/enQtNDIyNjg5NzY2MTQ1LTk4OTE4ZjdiMGFmMDlhNWM2ZWJkMmM0MGQxMjNhODJlOWY1MjQzMmQ5MDEzOGM3YjM0YTJiZTc3MWY5MGNmZjI).

**Pull request closed without merging**
