### PR TITLE
Selecting mode and copy/paste

### PR DESCRIPTION
**Pull request by grikukan**

### CODE REVIEW

**Comment by shnupta** [comment]
I'm getting a weird behaviour when testing this. No keywords showing up?

**Comment by grikukan** [comment]
Same here. I'll try to fix now.

**Comment by grikukan** [comment]
Well, it was really stupid bug :)

**Comment by shnupta** [comment]
Haha, no worries :) How is the pasting working for you? Mine has only worked correctly about 2 out of 10 times.

**Comment by grikukan** [comment]
I believe it should be better now.

**Comment by shnupta** [comment]
Awesome, looks like it is working great!

**Pull request merged**
