### PR TITLE
Add tags based movement

### PR DESCRIPTION
**Pull request by yashjakhotiya**
Added code for tags based movement. CTRL_M moves ahead (e.g. to a function definition, like CTRL_] in vim), CTRL_N moves back (like CTRL_t in vim). The movement can be nested. Used a stack to implement that. 

A tags file has to be present for the functionality to work. `cd` to your code directory and run `ctags -R *`.

There are various nitty-gritty's in implementing tags-based movement, like handling situations like trying to move back when the tag stack is empty or trying to go to a function defined in another file without saving the current one. I have tried including all of them. If you want to know why I wrote a specific line of code, feel free to shoot me an email.

### CODE REVIEW

**Comment by yashjakhotiya** [comment]
Sure. I would provide the documentation to you. In the meanwhile, could you please resolve a minor conflict. Can you shift the line `editing_row *find_row(int at);` in bric.h to the `
// Editor Rows Implementation` section. So, that you are able to merge this commit and then we all can refactor the entire code into smaller understandable modules.

**Comment by shnupta** [comment]
Cool thank you! Thanks for that extra bit of work too. Looks like we are really progressing here!

**Comment by shnupta** [comment]
Looks like you need to update some of your code to follow the new linked-list implementation. I suggest getting in contact with @DreamTheater2016 and/or looking at PR #63

**Comment by yashjakhotiya** [comment]
Updated the code to follow the new linked-list implementation. Things turned ugly while rebasing. Had to delete that repo. Created a new one.
Created a PR from the new repo. 
Able to merge now. 
The tags functionality works smoothly.
Have a look at PR #69 and let me know.

**Pull request merged**
