### PR TITLE
New syntax highlighting for Javascript

### PR DESCRIPTION
**Pull request by mohamessi**

### CODE REVIEW

**Comment by mohamessi** [comment]
We added the reserved keywords for Javascript from Mozilla Developer Network and W3C School.

**Comment by shnupta** [comment]
Cool, nice work!:)

**Comment by shnupta** [comment]
Do you think you could pull the latest commit quickly then update this PR please?:) Nice work otherwise though

**Comment by mohamessi** [comment]
Thanks you. I have pull the latest commit.

**Comment by shnupta** [comment]
Cool, thank you!

**Pull request merged**
