### PR TITLE
Added moving cursor to end of line when end button is pressed.

### PR DESCRIPTION
**Pull request by grikukan**

### CODE REVIEW

**Comment by shnupta** [comment]
Great work!! Could you start the line numbers from 1?

**Comment by grikukan** [comment]
Done. I'll think about wraps

**Comment by shnupta** [comment]
Awesome, okay cool. Only cause after a little testing there were some problems with lines wrapping but not actually being able to get to the wrapped text

**Comment by grikukan** [comment]
Seems, it works now.

**Comment by shnupta** [comment]
Works great!

**Pull request merged**
