### PR TITLE
tagstack.c:fix curr warning

### PR DESCRIPTION
**Pull request by andy5995**
This fixes the warning

```
tagstack.c: In function ‘pop’:
tagstack.c:37:10: warning: ‘curr’ may be used uninitialized in this
function [-Wmaybe-uninitialized]
curr->p = NULL;
```

https://travis-ci.com/shnupta/bric/jobs/143067788#L512

I'm not sure if this is a clean fix. I'm not yet familiar enough with
bric to test it properly (and the use of calloc() is still a bit
mysterious to me). The only things I did to test it was to build it
(warning went away), then open a file with bric.

### CODE REVIEW

**Comment by shnupta** [comment]
Yeah, they should be initialised first.What do you me when you say it is mysterious to you?

**Comment by andy5995** [comment]
>What do you me when you say it is mysterious to you?

I mean I still get confused sometimes about memory management in C, and the use of pointers and calloc/malloc.

Have you ever noticed on stackexchange the answers to programming questions? Someone will answer a question, then a 2nd person comes along and says, "no, that's not safe, this is the best way".. then a 3rd person comes along and says, "no, that's not safe either, do it this way".. And those answers are interspersed with a lot of comments that negate all 3 answers, lol. cc @sexybiggetje

Casey, could you explain to me a good way I could test the pop function in tagstack.c?

**Comment by shnupta** [comment]
> Have you ever noticed on stackexchange the answers to programming questions? Someone will answer a question, then a 2nd person comes along and says, "no, that's not safe, this is the best way".. then a 3rd person comes along and says, "no, that's not safe either, do it this way"

Yup, I've seen plenty of those haha. In this case, I would assume the reason for using `calloc` would be so that the stack is initialized with zeroed out memory values, as that's the main difference between `calloc` and `malloc` I believe.

I wasn't the author of the tags implementation and it was a long time ago that I reviewed and merged the PR but I'll go through the code and come back to you:)

**Comment by andy5995** [comment]
ok, so you are in the same boat as me, atm.. We're not sure if my patch would have any unintended side effects yet?

**Comment by shnupta** [comment]
It seems we are, yes. I don't see why initialising it would make a difference - however I was going to say (before your latest commit) that the sizeof a tagstack may be different than the one passed in.

**Comment by andy5995** [comment]
>There is documentation on how to use it here though: https://github.com/shnupta/bric/blob/development/src/modules/tag/documentation

Oh, I'll check out out soon. Should be what I need.

>however, I was going to say (before your latest commit) that the sizeof a tagstack may be different than the one passed in.

I think we're on the right track, but need to give it a little more thought.. and testing which I should be able to do after I review the link you gave me. I see that foo and curr are structures so may need to reconsider how the malloc statement is laid out.

https://github.com/shnupta/bric/blob/1046e8b6bf4d11434d9099c401619cc2c7e85469/src/modules/tag/tagstack.h#L9

**Comment by andy5995** [comment]
I read that link but I was having some problems troubleshooting this. Turns out that the default "ctags" on my PC is not the correct "ctags"

https://stackoverflow.com/questions/2968542/the-ctags-command-doesnt-recurse-saying-it-is-not-a-regular-file

Before I installed 'exuberant-ctags`, bric was segfaulting (even w/o my patch).

So now I believe I have a proper tags file.

I'll update this doc with my PR
https://github.com/shnupta/bric/blob/development/src/modules/tag/documentation

**Pull request merged**
