### PR TITLE
Added File Locking

### PR DESCRIPTION
**Pull request by doztrock**
I've remade the commit, I've added the file locking algorithm to avoid errors when editing files.

### CODE REVIEW

**Comment by doztrock** [comment]
Hope it helps, please contact if you have questions!

**Comment by shnupta** [comment]
Sorry about this @doztrock . Working too early in the morning on this doesn't help. You'll need to revert those two commits I've made to your branch as there were some errors with the last merge. I'll let you know when you should merge the changes with your branch and submit again.

**Comment by doztrock** [comment]
I've resolved the conflicts, could you please check it? You could ask me anything! 

Regards :)

**Comment by shnupta** [comment]
Hi @doztrock , I've only had a quick look so far but could you avoid using 'strdup' is my only request for now as we are trying to be C99 compliant. Thanks

**Comment by doztrock** [comment]
@shnupta OK, I'll correct it!

**Comment by doztrock** [comment]
@shnupta Done! I've removed the strdup

**Comment by shnupta** [comment]
Cool that looks good thank you! I'll give the code a read through tonight and tomorrow as much as possible and should merge by Sunday. Thank you again:)

**Comment by doztrock** [comment]
Hey @shnupta , based in what have been talked in comments about the "Road ahead" issue, I've make my first contribution isolating the locking-file functions in a different sources files and i've made some modification in the `Makefile` file to handle it, hope you like it!

Regards

**Comment by doztrock** [comment]
@shnupta Also, i've used a kind of documentation i've used some time ago, I hope you like the style of comments for my functions. Any comments are welcome!

**Comment by shnupta** [comment]
Hi @doztrock ,
The changes look perfect. Thanks for your comment on the road ahead issue, just about to reply now. I think when we begin the larger refactor we should take a similar route to code commenting like you've done as this will really make the code easy to work on. All I can say is thank you very much and keep it up!

**Pull request merged**
